CREATE TABLE `Persons`(
	`Id` VARCHAR(36) NOT NULL,
	`FirstName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,restwithaspnetpersons
	`Address` VARCHAR(50) NULL DEFAULT NULL,
	`Gender` INT(1) UNSIGNED NOT NULL
)
ENGINE=INNODB;